/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AviatorRouteImport } from './routes/aviator'
import { Route as BookingCodeRouteImport } from './routes/booking-code'
import { Route as CasinoRouteImport } from './routes/casino'
import { Route as CrashRouteImport } from './routes/crash'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as LiveRouteImport } from './routes/live'
import { Route as SportsRouteImport } from './routes/sports'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'
import { Route as MyBetsIndexRouteImport } from './routes/my-bets.index'
import { Route as MyBetsBetIdRouteImport } from './routes/my-bets.$betId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AviatorRoute = AviatorRouteImport.update({
  id: '/aviator',
  path: '/aviator',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCodeRoute = BookingCodeRouteImport.update({
  id: '/booking-code',
  path: '/booking-code',
  getParentRoute: () => rootRouteImport,
} as any)
const CasinoRoute = CasinoRouteImport.update({
  id: '/casino',
  path: '/casino',
  getParentRoute: () => rootRouteImport,
} as any)
const CrashRoute = CrashRouteImport.update({
  id: '/crash',
  path: '/crash',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const SportsRoute = SportsRouteImport.update({
  id: '/sports',
  path: '/sports',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsIndexRoute = MyBetsIndexRouteImport.update({
  id: '/my-bets/',
  path: '/my-bets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyBetsBetIdRoute = MyBetsBetIdRouteImport.update({
  id: '/my-bets/$betId',
  path: '/my-bets/$betId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviator': typeof AviatorRoute
  '/booking-code': typeof BookingCodeRoute
  '/casino': typeof CasinoRoute
  '/crash': typeof CrashRoute
  '/deposit': typeof DepositRoute
  '/live': typeof LiveRoute
  '/sports': typeof SportsRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/my-bets/$betId': typeof MyBetsBetIdRoute
  '/my-bets/': typeof MyBetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviator': typeof AviatorRoute
  '/booking-code': typeof BookingCodeRoute
  '/casino': typeof CasinoRoute
  '/crash': typeof CrashRoute
  '/deposit': typeof DepositRoute
  '/live': typeof LiveRoute
  '/sports': typeof SportsRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/my-bets/$betId': typeof MyBetsBetIdRoute
  '/my-bets': typeof MyBetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/aviator': typeof AviatorRoute
  '/booking-code': typeof BookingCodeRoute
  '/casino': typeof CasinoRoute
  '/crash': typeof CrashRoute
  '/deposit': typeof DepositRoute
  '/live': typeof LiveRoute
  '/sports': typeof SportsRoute
  '/transactions': typeof TransactionsRoute
  '/withdraw': typeof WithdrawRoute
  '/match/$matchId': typeof MatchMatchIdRoute
  '/my-bets/$betId': typeof MyBetsBetIdRoute
  '/my-bets/': typeof MyBetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/aviator'
    | '/booking-code'
    | '/casino'
    | '/crash'
    | '/deposit'
    | '/live'
    | '/sports'
    | '/transactions'
    | '/withdraw'
    | '/match/$matchId'
    | '/my-bets/$betId'
    | '/my-bets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/aviator'
    | '/booking-code'
    | '/casino'
    | '/crash'
    | '/deposit'
    | '/live'
    | '/sports'
    | '/transactions'
    | '/withdraw'
    | '/match/$matchId'
    | '/my-bets/$betId'
    | '/my-bets'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/aviator'
    | '/booking-code'
    | '/casino'
    | '/crash'
    | '/deposit'
    | '/live'
    | '/sports'
    | '/transactions'
    | '/withdraw'
    | '/match/$matchId'
    | '/my-bets/$betId'
    | '/my-bets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AviatorRoute: typeof AviatorRoute
  BookingCodeRoute: typeof BookingCodeRoute
  CasinoRoute: typeof CasinoRoute
  CrashRoute: typeof CrashRoute
  DepositRoute: typeof DepositRoute
  LiveRoute: typeof LiveRoute
  SportsRoute: typeof SportsRoute
  TransactionsRoute: typeof TransactionsRoute
  WithdrawRoute: typeof WithdrawRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
  MyBetsBetIdRoute: typeof MyBetsBetIdRoute
  MyBetsIndexRoute: typeof MyBetsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviator': {
      id: '/aviator'
      path: '/aviator'
      fullPath: '/aviator'
      preLoaderRoute: typeof AviatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-code': {
      id: '/booking-code'
      path: '/booking-code'
      fullPath: '/booking-code'
      preLoaderRoute: typeof BookingCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casino': {
      id: '/casino'
      path: '/casino'
      fullPath: '/casino'
      preLoaderRoute: typeof CasinoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crash': {
      id: '/crash'
      path: '/crash'
      fullPath: '/crash'
      preLoaderRoute: typeof CrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sports': {
      id: '/sports'
      path: '/sports'
      fullPath: '/sports'
      preLoaderRoute: typeof SportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets/': {
      id: '/my-bets/'
      path: '/my-bets'
      fullPath: '/my-bets/'
      preLoaderRoute: typeof MyBetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-bets/$betId': {
      id: '/my-bets/$betId'
      path: '/my-bets/$betId'
      fullPath: '/my-bets/$betId'
      preLoaderRoute: typeof MyBetsBetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AviatorRoute: AviatorRoute,
  BookingCodeRoute: BookingCodeRoute,
  CasinoRoute: CasinoRoute,
  CrashRoute: CrashRoute,
  DepositRoute: DepositRoute,
  LiveRoute: LiveRoute,
  SportsRoute: SportsRoute,
  TransactionsRoute: TransactionsRoute,
  WithdrawRoute: WithdrawRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
  MyBetsBetIdRoute: MyBetsBetIdRoute,
  MyBetsIndexRoute: MyBetsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
